## Seek, Create, Update, and Destroy (0:20)

In [1]:
from sqlalchemy import create_engine
import pandas as pd
from warnings import filterwarnings
import pymysql
filterwarnings('ignore', category=pymysql.Warning)
import os

In [2]:
engine = create_engine('mysql+pymysql://root:AQib.21Talib@localhost')  # connect to server
engine.execute("create database if not exists firepower") #create db
engine = create_engine('mysql+pymysql://root:AQib.21Talib@localhost/firepower')

In [3]:
def RunSQL(sql_command):
    connection = pymysql.connect(host='localhost',
                             user='root',
                             password='AQib.21Talib',
                             db='firepower',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
    try:
        with connection.cursor() as cursor:
            commands = sql_command.split(';')
            for command in commands:
                if command == '\n': continue
                cursor.execute(command + ';')
                connection.commit()
    except Exception as e: 
        print(e)
    finally:
        connection.close()

In [4]:
file_name = os.path.join('resources', 'GlobalFirePower.csv')
df = pd.read_csv(file_name)
df.head()

,Country,ISO3,Rank,Total Population,Manpower Available,Fit-for-Service,Reaching Military Age,Total Military Personnel,Active Personnel,Reserve Personnel,...,Railway Coverage (km),Serivecable Airports,Defense Budget,External Debt,Foreign Exchange / Gold,Purchasing Power Parity,Square Land Area (km),Coastline (km),Shared Borders (km),Waterways (km)
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,1373650,990025,...,224792,13513,587800,17910000,117600,18560000,9826675,19924,12048,41009
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,798527,2572500,...,87157,1218,44600,514800,365500,3745000,17098242,37653,22408,102000
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,2260000,1452500,...,86000,507,161700,983500,3092000,21270000,9596961,14500,22457,110000
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,1362500,2844750,...,63974,346,51000,507000,359100,8721000,3287263,7000,13888,14500
4,France,FRA,5,66836154,30000000,23750000,775000,387635,204000,183635,...,29640,464,35000,5360000,138200,2737000,643801,4853,4072,8501

In [5]:
df.columns = df.columns.str.replace('\s+', '_')

In [6]:
df.to_sql(con=engine, name='military', if_exists='replace', index=False)

In [7]:
new_df = pd.read_sql_query('select * from military', engine)
new_df

,Country,ISO3,Rank,Total_Population,Manpower_Available,Fit-for-Service,Reaching_Military_Age,Total_Military_Personnel,Active_Personnel,Reserve_Personnel,...,Railway_Coverage_(km),Serivecable_Airports,Defense_Budget,External_Debt,Foreign_Exchange_/_Gold,Purchasing_Power_Parity,Square_Land_Area_(km),Coastline_(km),Shared_Borders_(km),Waterways_(km)
0,United States,USA,1,323995528,145215000,120025000,4220000,2363675,1373650,990025,...,224792,13513,587800,17910000,117600,18560000,9826675,19924,12048,41009
1,Russia,RUS,2,142355415,70000000,47000000,1355000,3371027,798527,2572500,...,87157,1218,44600,514800,365500,3745000,17098242,37653,22408,102000
2,China,CHN,3,1373541278,750000000,619000000,19550000,3712500,2260000,1452500,...,86000,507,161700,983500,3092000,21270000,9596961,14500,22457,110000
3,India,IND,4,1266883598,616000000,489600000,22900000,4207250,1362500,2844750,...,63974,346,51000,507000,359100,8721000,3287263,7000,13888,14500
4,France,FRA,5,66836154,30000000,23750000,775000,387635,204000,183635,...,29640,464,35000,5360000,138200,2737000,643801,4853,4072,8501
5,United Kingdom,UKD,6,64430428,30000000,24040000,750000,232675,151175,81500,...,16454,460,45700,8126000,129600,2788000,243610,12429,443,3200
6,Japan,JPN,7,126702133,54000000,44000000,1215000,311875,248575,63300,...,27182,175,43800,3240000,1233000,4932000,377915,29751,0,1770
7,Turkey,TUR,8,80274604,41640000,35010000,1375000,743415,382850,360565,...,8699,98,8208,410400,115000,1670000,783562,7200,2816,1200
8,Germany,GER,9,80722792,37000000,29540000,791000,210000,180000,30000,...,41981,539,39200,5326000,173700,3979000,357022,2389,3694,7467
9,Egypt,EGP,10,94666993,42000000,35306000,1535000,1329250,454250,875000,...,5083,83,4400,50670,15060,1105000,1001450,2450,2612,3500
10,Italy,ITA,11,62007540,28000000,22600000,570000,267500,247500,20000,...,20255,129,34000,2444000,130600,2221000,301340,7600,1836,2400
11,South Korea,SKO,12,50924172,25610000,21035000,690000,5829750,627500,5202250,...,3381,111,43800,385600,372700,1929000,99720,2413,237,1600
12,Pakistan,PAK,13,201995540,95000000,75325000,4345000,919000,637000,282000,...,7791,151,7000,64040,20530,988200,796095,1046,7257,25220
13,Indonesia,INO,14,258316051,130000000,107540000,4500000,975750,435750,540000,...,5042,673,6900,344700,106400,3028000,1904569,54716,2958,21579
14,Israel,ISR,15,8174527,3600000,3000000,122000,718250,168250,550000,...,975,47,15500,91080,97220,297000,20770,273,1068,Minimum not met.
15,Vietnam,VTN,16,95261021,50650000,41505000,1640000,5488500,448500,5040000,...,2632,45,3365,78880,34660,594900,331210,3444,4616,17702
16,Brazil,BRA,17,205823665,107000000,84000000,3410000,1987000,334500,1652500,...,28538,4093,24500,544100,352100,3135000,8514877,7491,16145,50000
17,Taiwan,TAI,18,23464787,12200000,10030000,325000,1932500,257500,1675000,...,1580,37,10725,155400,456900,1125000,35980,1566,0,3720
18,Poland,POL,19,38523261,19000000,15585000,435000,184650,109650,75000,...,19428,126,9360,344800,90210,1052000,312685,440,2845,3997
19,Thailand,THA,20,68200824,35500000,27500000,1045000,627425,335425,292000,...,4071,101,5390,137100,181400,1161000,513120,3219,5673,4000
20,Iran,IRN,21,82801633,47000000,39570000,1400000,934000,534000,400000,...,8442,319,6300,7116,135500,1459000,1648195,2440,5894,850
21,Australia,AUS,22,22992654,10700000,8800000,280000,81000,60000,21000,...,38445,480,24100,1692000,54300,1189000,7741220,25760,0,2000
22,North Korea,NKO,23,25115311,13000000,10100000,415000,6445000,945000,5500000,...,5242,82,7500,5000,6000,40000,120538,2495,1607,2250
23,Saudi Arabia,SAR,24,28160273,15300000,14000000,510000,256000,231000,25000,...,1378,214,56725,200900,553700,1731000,2149690,2640,4272,Minimum not met.
24,Algeria,ALG,25,40263711,20400000,17250000,675000,792350,520000,272350,...,3973,157,10570,5934,115000,609400,2381741,998,6734,Minimum not met.
25,Canada,CAN,26,35362905,16000000,13025000,425000,111250,79000,32250,...,46552,1467,15500,1608000,82500,1674000,9984670,202080,8893,636
26,Spain,SPA,27,48563476,23000000,18725000,423000,174700,124100,50600,...,15293,150,11600,2094000,53970,1690000,505370,4964,1953,1000
27,Greece,GRE,28,10773253,5000000,4050000,105000,413750,161500,252250,...,2548,77,6540,506600,6026,290500,131957,13676,1110,6
28,Sweden,SWE,29,9880604,4065000,3400000,110000,43875,21875,22000,...,11633,231,6215,939900,58110,498100,450295,3218,2211,2052
29,Ukraine,UKR,30,44209733,22250000,15700000,482000,1182000,182000,1000000,...,21658,187,4880,127700,16010,349800,603550,2782,5618,2150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,Uruguay,URU,104,3351016,1555000,1305000,54500,25900,25000,900,...,1641,133,490,21300,14850,73930,176215,660,1591,1600
104,Paraguay,PAR,105,6862812,3360000,2845000,146000,183200,10700,172500,...,36,799,145,15420,6059,64120,406752,Landlocked,4655,3100
105,Honduras,HON,106,8893259,4100000,3066000,190000,76000,12000,64000,...,44,103,205,8042,3846,43190,112090,832,1575,465
106,Botswana,BOT,107,2209208,948157,565101,22208,9000,9000,0,...,0,74,470,2386,7682,35900,581730,Landlocked,4347,Minimum not met.
107,Kyrgyzstan,KYR,108,5727553,3000000,2377000,111000,23700,13700,10000,...,470,28,240,7728,1838,21010,199951,Landlocked,4573,600
108,Mozambique,MOZ,109,25930150,4600000,5620000,555000,11200,11200,0,...,4787,98,86,9554,1541,35310,799380,2470,4783,460
109,Estonia,EST,110,1258545,600000,465000,13000,35000,5000,30000,...,1196,18,335,19050,475,38700,45228,3794,657,335
110,Cameroon,CAM,111,24360803,9300000,5515000,430000,25000,15000,10000,...,1245,33,370,7375,2416,77240,475440,400,5018,Minimum not met.
111,Tajikistan,TAJ,112,8330946,4035000,3200000,152000,14900,7400,7500,...,680,24,75,3976,416,25810,143100,Landlocked,4130,200
112,Slovenia,SLV,113,1978029,942000,775000,20000,15500,7500,8000,...,1228,16,790,51650,851,66130,20273,47,1211,Minimum not met.
113,Niger,NGR,114,18638600,6600000,4415000,370000,11000,5500,5500,...,0,30,85,2729,903,20270,1267000,Landlocked,5834,300
114,Nicaragua,NIC,115,5966798,3005000,2565000,140000,13000,13000,0,...,0,147,44,11100,2442,33490,130370,910,1253,2220
115,Ivory Coast,IVC,116,23740424,10300000,6556000,490000,17450,17450,0,...,660,27,440,15840,4952,87120,322463,515,3458,980
116,Mali,MAL,117,17467108,6000000,3795000,320000,15500,7500,8000,...,593,25,76,3626,3074,38090,1240192,Landlocked,7908,0
117,Republic of the Congo,ROC,118,4852412,1900000,1150000,100000,12000,10000,2000,...,886,27,135,4817,1989,30270,342000,169,5008,1120
118,Madagascar,MAD,119,24430325,9900000,7075000,500000,21600,13500,8100,...,854,83,56,4007,780,37490,587040,4828,0,600
119,Gabon,GAB,120,1738541,705000,400000,36000,4850,4850,0,...,649,44,81,5158,1585,36220,267667,885,3261,1600
120,Bosnia and Herzegovina,BOS,121,3861912,2400000,2000000,52000,12750,12750,0,...,601,24,250,9768,4800,42530,51197,20,1543,Minimum not met.
121,Macedonia,MAC,122,2100025,1046540,871803,31064,24055,8055,16000,...,700,10,108,7680,2576,30130,25713,Landlocked,838,280
122,Dominican Republic,DOM,123,10606865,3535621,1767810,105855,65925,50925,15000,...,496,36,110,26050,6924,161900,48320,1288,376,350
123,Laos,LAO,124,7019073,3200000,2302000,145000,130000,30000,100000,...,0,41,18,11980,1024,40960,236800,Landlocked,5274,4600
124,El Salvador,ESL,125,6156670,3100000,2455000,141000,47000,20000,27000,...,283,68,165,14900,3201,54790,21041,307,590,Minimum not met.
125,Panama,PAN,126,3705246,900000,1500000,64000,34000,12000,22000,...,76,117,145,22900,3878,93120,75420,2490,687,800
126,Namibia,NAM,127,2436469,570000,665000,53000,15500,9500,6000,...,2626,112,120,6515,1762,27040,824292,1572,4220,Minimum not met.
127,Somalia,SOM,128,10817354,2700000,2700000,203000,15900,15900,0,...,0,61,58,3054,30,4431,637657,3025,2385,Minimum not met.
128,Central African Republic,CAR,129,5507257,2300000,1320000,110000,5825,5825,0,...,0,39,18,686,4128,3206,622984,Landlocked,5920,2800
129,Mauritania,MAU,130,3677293,1523335,1061515,72942,20870,15870,5000,...,728,30,39,3585000,1186,16710,1030700,754,5002,Minimum not met.
130,Sierra Leone,SIE,131,6018888,1402400,835830,32848,10750,10750,0,...,0,8,13,1561,2332,10640,71740,402,1093,800
131,Suriname,SUR,132,585824,131700,77100,3030,2270,2170,100,...,0,55,67,1439,393,8547,163820,386,1907,1200
132,Bhutan,BUT,133,750125,175000,104300,4100,7500,7500,0,...,0,2,10,2261,15,6432,38394,Landlocked,1136,Minimum not met.

In [8]:
new_df.columns

Index(['Country', 'ISO3', 'Rank', 'Total_Population', 'Manpower_Available',
       'Fit-for-Service', 'Reaching_Military_Age', 'Total_Military_Personnel',
       'Active_Personnel', 'Reserve_Personnel', 'Total_Aircraft_Strength',
       'Fighter_Aircraft', 'Attack_Aircraft', 'Transport_Aircraft',
       'Trainer_Aircraft', 'Total_Helicopter_Strength', 'Attack_Helicopters',
       'Combat_Tanks', 'Armored_Fighting_Vehicles', 'Self-Propelled_Artillery',
       'Towed_Artillery', 'Rocket_Projectors', 'Total_Naval_Assets',
       'Aircraft_Carriers', 'Frigates', 'Destroyers', 'Corvettes',
       'Submarines', 'Patrol_Craft', 'Mine_Warfare_Vessels',
       'Production_(bbl/dy)', 'Consumption_(bbl/dy)', 'Proven_Reserves_(bbl)',
       'Labor_Force', 'Merchant_Marine_Strength', 'Major_Ports_/_Terminals',
       'Roadway_Coverage_(km)', 'Railway_Coverage_(km)',
       'Serivecable_Airports', 'Defense_Budget', 'External_Debt',
       'Foreign_Exchange_/_Gold', 'Purchasing_Power_Parity',
       'Square_Land_Area_(km)', 'Coastline_(km)', 'Shared_Borders_(km)',
       'Waterways_(km)'],
      dtype='object')

* Find all of those rows that have a "Reserve_Personnel" of 0 and then remove these rows from the dataset.

* Use the `delete from` sql command.

In [9]:
# TODO: Fill in the SQL Query Below
sql_command = """
delete from military 
where Reserve_Personnel = 0;
"""
RunSQL(sql_command)

* Every country in the world at least deserves one "FighterAircraft". Only seems fair. Lets add one to each nation that has none.

In [12]:
# TODO: Fill in the SQL Query Below..
# something along the lines of UPDATE table SET value=1 WHERE value=0
sql_command = """
update military 
set Fighter_Aircraft=1 
where Fighter_Aircraft=0
"""
RunSQL(sql_command)

* Oh no! By updating this column, the values within "TotalAircraftStrength" column are now off for those nations! We've got to [add one](https://stackoverflow.com/a/2680352) to the original number.

In [13]:
sql_command = """
update military
set Total_Aircraft_Strength = Total_Aircraft_Strength + 1
where Fighter_Aircraft=1
"""
RunSQL(sql_command)

* A new nation has been founded and you are declared its leader! Congratulations! Unfortunately for you, every other nation is now looking to take over your land. Perform some calcuations to find the [Averages](https://www.w3schools.com/sql/sql_count_avg_sum.asp) for each the "Total" columns, take note of them, and then set those as the values for your nation's military.

In [18]:
# avg(Total_military_Personal)
new_df1 = pd.read_sql_query('select avg(Total_Military_Personnel) from military', engine)
new_df1

   avg(Total_Military_Personnel)
0                    524357.6071

In [19]:
# avg(Total_Aircraft_Strength)
new_df2 = pd.read_sql_query('select avg(Total_Aircraft_Strength) from military', engine)
new_df2

   avg(Total_Aircraft_Strength)
0                      456.5625

In [20]:
# avg(Total_Helicopter_Strength)
new_df3 = pd.read_sql_query('select avg(Total_Helicopter_Strength) from military', engine)
new_df3

   avg(Total_Helicopter_Strength)
0                        182.6518

In [21]:
# avg(Total_Population)
new_df4 = pd.read_sql_query('select avg(Total_Population) from military', engine)
new_df4

   avg(Total_Population)
0           6.006902e+07

* With the averages formed above for each the "Total" columns, take note of them, and then set those as the values for your nation's military. Insert these values into the database with your country's name

In [22]:
#TODO
sql_command = """
insert into military (Country, Total_Military_Personnel, Total_Aircraft_Strength, Total_Helicopter_Strength, Total_Population)
values ("Waynes World", 524357.6071, 456.5625, 182.6518, 6.006902e+07)
"""
RunSQL(sql_command)


* **Bonus**:

    * After creating your new nation and some parts of your military strategies, go through each column in the newly created row and update their values in any way that you desire!

In [23]:
new_df5 = pd.read_sql_query('select * from military', engine)
new_df5

,Country,ISO3,Rank,Total_Population,Manpower_Available,Fit-for-Service,Reaching_Military_Age,Total_Military_Personnel,Active_Personnel,Reserve_Personnel,...,Railway_Coverage_(km),Serivecable_Airports,Defense_Budget,External_Debt,Foreign_Exchange_/_Gold,Purchasing_Power_Parity,Square_Land_Area_(km),Coastline_(km),Shared_Borders_(km),Waterways_(km)
0,United States,USA,1.0,323995528,145215000.0,120025000.0,4220000.0,2363675,1373650.0,990025.0,...,224792.0,13513.0,587800.0,17910000.0,117600.0,18560000.0,9826675.0,19924,12048.0,41009
1,Russia,RUS,2.0,142355415,70000000.0,47000000.0,1355000.0,3371027,798527.0,2572500.0,...,87157.0,1218.0,44600.0,514800.0,365500.0,3745000.0,17098242.0,37653,22408.0,102000
2,China,CHN,3.0,1373541278,750000000.0,619000000.0,19550000.0,3712500,2260000.0,1452500.0,...,86000.0,507.0,161700.0,983500.0,3092000.0,21270000.0,9596961.0,14500,22457.0,110000
3,India,IND,4.0,1266883598,616000000.0,489600000.0,22900000.0,4207250,1362500.0,2844750.0,...,63974.0,346.0,51000.0,507000.0,359100.0,8721000.0,3287263.0,7000,13888.0,14500
4,France,FRA,5.0,66836154,30000000.0,23750000.0,775000.0,387635,204000.0,183635.0,...,29640.0,464.0,35000.0,5360000.0,138200.0,2737000.0,643801.0,4853,4072.0,8501
5,United Kingdom,UKD,6.0,64430428,30000000.0,24040000.0,750000.0,232675,151175.0,81500.0,...,16454.0,460.0,45700.0,8126000.0,129600.0,2788000.0,243610.0,12429,443.0,3200
6,Japan,JPN,7.0,126702133,54000000.0,44000000.0,1215000.0,311875,248575.0,63300.0,...,27182.0,175.0,43800.0,3240000.0,1233000.0,4932000.0,377915.0,29751,0.0,1770
7,Turkey,TUR,8.0,80274604,41640000.0,35010000.0,1375000.0,743415,382850.0,360565.0,...,8699.0,98.0,8208.0,410400.0,115000.0,1670000.0,783562.0,7200,2816.0,1200
8,Germany,GER,9.0,80722792,37000000.0,29540000.0,791000.0,210000,180000.0,30000.0,...,41981.0,539.0,39200.0,5326000.0,173700.0,3979000.0,357022.0,2389,3694.0,7467
9,Egypt,EGP,10.0,94666993,42000000.0,35306000.0,1535000.0,1329250,454250.0,875000.0,...,5083.0,83.0,4400.0,50670.0,15060.0,1105000.0,1001450.0,2450,2612.0,3500
10,Italy,ITA,11.0,62007540,28000000.0,22600000.0,570000.0,267500,247500.0,20000.0,...,20255.0,129.0,34000.0,2444000.0,130600.0,2221000.0,301340.0,7600,1836.0,2400
11,South Korea,SKO,12.0,50924172,25610000.0,21035000.0,690000.0,5829750,627500.0,5202250.0,...,3381.0,111.0,43800.0,385600.0,372700.0,1929000.0,99720.0,2413,237.0,1600
12,Pakistan,PAK,13.0,201995540,95000000.0,75325000.0,4345000.0,919000,637000.0,282000.0,...,7791.0,151.0,7000.0,64040.0,20530.0,988200.0,796095.0,1046,7257.0,25220
13,Indonesia,INO,14.0,258316051,130000000.0,107540000.0,4500000.0,975750,435750.0,540000.0,...,5042.0,673.0,6900.0,344700.0,106400.0,3028000.0,1904569.0,54716,2958.0,21579
14,Israel,ISR,15.0,8174527,3600000.0,3000000.0,122000.0,718250,168250.0,550000.0,...,975.0,47.0,15500.0,91080.0,97220.0,297000.0,20770.0,273,1068.0,Minimum not met.
15,Vietnam,VTN,16.0,95261021,50650000.0,41505000.0,1640000.0,5488500,448500.0,5040000.0,...,2632.0,45.0,3365.0,78880.0,34660.0,594900.0,331210.0,3444,4616.0,17702
16,Brazil,BRA,17.0,205823665,107000000.0,84000000.0,3410000.0,1987000,334500.0,1652500.0,...,28538.0,4093.0,24500.0,544100.0,352100.0,3135000.0,8514877.0,7491,16145.0,50000
17,Taiwan,TAI,18.0,23464787,12200000.0,10030000.0,325000.0,1932500,257500.0,1675000.0,...,1580.0,37.0,10725.0,155400.0,456900.0,1125000.0,35980.0,1566,0.0,3720
18,Poland,POL,19.0,38523261,19000000.0,15585000.0,435000.0,184650,109650.0,75000.0,...,19428.0,126.0,9360.0,344800.0,90210.0,1052000.0,312685.0,440,2845.0,3997
19,Thailand,THA,20.0,68200824,35500000.0,27500000.0,1045000.0,627425,335425.0,292000.0,...,4071.0,101.0,5390.0,137100.0,181400.0,1161000.0,513120.0,3219,5673.0,4000
20,Iran,IRN,21.0,82801633,47000000.0,39570000.0,1400000.0,934000,534000.0,400000.0,...,8442.0,319.0,6300.0,7116.0,135500.0,1459000.0,1648195.0,2440,5894.0,850
21,Australia,AUS,22.0,22992654,10700000.0,8800000.0,280000.0,81000,60000.0,21000.0,...,38445.0,480.0,24100.0,1692000.0,54300.0,1189000.0,7741220.0,25760,0.0,2000
22,North Korea,NKO,23.0,25115311,13000000.0,10100000.0,415000.0,6445000,945000.0,5500000.0,...,5242.0,82.0,7500.0,5000.0,6000.0,40000.0,120538.0,2495,1607.0,2250
23,Saudi Arabia,SAR,24.0,28160273,15300000.0,14000000.0,510000.0,256000,231000.0,25000.0,...,1378.0,214.0,56725.0,200900.0,553700.0,1731000.0,2149690.0,2640,4272.0,Minimum not met.
24,Algeria,ALG,25.0,40263711,20400000.0,17250000.0,675000.0,792350,520000.0,272350.0,...,3973.0,157.0,10570.0,5934.0,115000.0,609400.0,2381741.0,998,6734.0,Minimum not met.
25,Canada,CAN,26.0,35362905,16000000.0,13025000.0,425000.0,111250,79000.0,32250.0,...,46552.0,1467.0,15500.0,1608000.0,82500.0,1674000.0,9984670.0,202080,8893.0,636
26,Spain,SPA,27.0,48563476,23000000.0,18725000.0,423000.0,174700,124100.0,50600.0,...,15293.0,150.0,11600.0,2094000.0,53970.0,1690000.0,505370.0,4964,1953.0,1000
27,Greece,GRE,28.0,10773253,5000000.0,4050000.0,105000.0,413750,161500.0,252250.0,...,2548.0,77.0,6540.0,506600.0,6026.0,290500.0,131957.0,13676,1110.0,6
28,Sweden,SWE,29.0,9880604,4065000.0,3400000.0,110000.0,43875,21875.0,22000.0,...,11633.0,231.0,6215.0,939900.0,58110.0,498100.0,450295.0,3218,2211.0,2052
29,Ukraine,UKR,30.0,44209733,22250000.0,15700000.0,482000.0,1182000,182000.0,1000000.0,...,21658.0,187.0,4880.0,127700.0,16010.0,349800.0,603550.0,2782,5618.0,2150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Armenia,ARM,93.0,3051250,1700000.0,1400000.0,45000.0,215700,44800.0,170900.0,...,869.0,11.0,225.0,8365.0,1512.0,26560.0,29743.0,Landlocked,1570.0,Minimum not met.
84,Bahrain,BAH,94.0,1378904,800000.0,680000.0,17120.0,47405,11600.0,35805.0,...,0.0,4.0,730.0,21160.0,3260.0,66370.0,760.0,161,0.0,Minimum not met.
85,Lithuania,LIT,95.0,2854235,1800000.0,1400000.0,40000.0,23015,16015.0,7000.0,...,1767.0,61.0,430.0,34480.0,1697.0,85790.0,65300.0,90,1545.0,441
86,Tanzania,TAN,96.0,52482726,10000000.0,11750000.0,1030000.0,110000,30000.0,80000.0,...,3689.0,166.0,220.0,15890.0,3771.0,150600.0,947300.0,1424,4161.0,Minimum not met.
87,Nepal,NEP,97.0,29033914,14600000.0,11210000.0,750000.0,157000,95000.0,62000.0,...,59.0,47.0,210.0,4990.0,8054.0,71520.0,147181.0,Landlocked,3159.0,Minimum not met.
88,Lebanon,LEB,98.0,6237738,2200000.0,1865000.0,72000.0,116000,96000.0,20000.0,...,401.0,8.0,1735.0,40740.0,47740.0,85160.0,10400.0,225,484.0,170
89,Guatemala,GUA,100.0,15189958,6600000.0,5518000.0,340000.0,106775,16775.0,90000.0,...,332.0,291.0,210.0,19090.0,8803.0,132300.0,108889.0,400,1667.0,990
90,New Zealand,NWZ,102.0,4474549,2100000.0,1675000.0,60000.0,11300,9000.0,2300.0,...,4128.0,123.0,1870.0,81390.0,18550.0,174800.0,267710.0,15134,0.0,Minimum not met.
91,Latvia,LAT,103.0,1965686,850000.0,850000.0,20500.0,17155,9155.0,8000.0,...,2239.0,42.0,280.0,40020.0,7507.0,50870.0,64589.0,498,1370.0,300
92,Uruguay,URU,104.0,3351016,1555000.0,1305000.0,54500.0,25900,25000.0,900.0,...,1641.0,133.0,490.0,21300.0,14850.0,73930.0,176215.0,660,1591.0,1600
93,Paraguay,PAR,105.0,6862812,3360000.0,2845000.0,146000.0,183200,10700.0,172500.0,...,36.0,799.0,145.0,15420.0,6059.0,64120.0,406752.0,Landlocked,4655.0,3100
94,Honduras,HON,106.0,8893259,4100000.0,3066000.0,190000.0,76000,12000.0,64000.0,...,44.0,103.0,205.0,8042.0,3846.0,43190.0,112090.0,832,1575.0,465
95,Kyrgyzstan,KYR,108.0,5727553,3000000.0,2377000.0,111000.0,23700,13700.0,10000.0,...,470.0,28.0,240.0,7728.0,1838.0,21010.0,199951.0,Landlocked,4573.0,600
96,Estonia,EST,110.0,1258545,600000.0,465000.0,13000.0,35000,5000.0,30000.0,...,1196.0,18.0,335.0,19050.0,475.0,38700.0,45228.0,3794,657.0,335
97,Cameroon,CAM,111.0,24360803,9300000.0,5515000.0,430000.0,25000,15000.0,10000.0,...,1245.0,33.0,370.0,7375.0,2416.0,77240.0,475440.0,400,5018.0,Minimum not met.
98,Tajikistan,TAJ,112.0,8330946,4035000.0,3200000.0,152000.0,14900,7400.0,7500.0,...,680.0,24.0,75.0,3976.0,416.0,25810.0,143100.0,Landlocked,4130.0,200
99,Slovenia,SLV,113.0,1978029,942000.0,775000.0,20000.0,15500,7500.0,8000.0,...,1228.0,16.0,790.0,51650.0,851.0,66130.0,20273.0,47,1211.0,Minimum not met.
100,Niger,NGR,114.0,18638600,6600000.0,4415000.0,370000.0,11000,5500.0,5500.0,...,0.0,30.0,85.0,2729.0,903.0,20270.0,1267000.0,Landlocked,5834.0,300
101,Mali,MAL,117.0,17467108,6000000.0,3795000.0,320000.0,15500,7500.0,8000.0,...,593.0,25.0,76.0,3626.0,3074.0,38090.0,1240192.0,Landlocked,7908.0,0
102,Republic of the Congo,ROC,118.0,4852412,1900000.0,1150000.0,100000.0,12000,10000.0,2000.0,...,886.0,27.0,135.0,4817.0,1989.0,30270.0,342000.0,169,5008.0,1120
103,Madagascar,MAD,119.0,24430325,9900000.0,7075000.0,500000.0,21600,13500.0,8100.0,...,854.0,83.0,56.0,4007.0,780.0,37490.0,587040.0,4828,0.0,600
104,Macedonia,MAC,122.0,2100025,1046540.0,871803.0,31064.0,24055,8055.0,16000.0,...,700.0,10.0,108.0,7680.0,2576.0,30130.0,25713.0,Landlocked,838.0,280
105,Dominican Republic,DOM,123.0,10606865,3535621.0,1767810.0,105855.0,65925,50925.0,15000.0,...,496.0,36.0,110.0,26050.0,6924.0,161900.0,48320.0,1288,376.0,350
106,Laos,LAO,124.0,7019073,3200000.0,2302000.0,145000.0,130000,30000.0,100000.0,...,0.0,41.0,18.0,11980.0,1024.0,40960.0,236800.0,Landlocked,5274.0,4600
107,El Salvador,ESL,125.0,6156670,3100000.0,2455000.0,141000.0,47000,20000.0,27000.0,...,283.0,68.0,165.0,14900.0,3201.0,54790.0,21041.0,307,590.0,Minimum not met.
108,Panama,PAN,126.0,3705246,900000.0,1500000.0,64000.0,34000,12000.0,22000.0,...,76.0,117.0,145.0,22900.0,3878.0,93120.0,75420.0,2490,687.0,800
109,Namibia,NAM,127.0,2436469,570000.0,665000.0,53000.0,15500,9500.0,6000.0,...,2626.0,112.0,120.0,6515.0,1762.0,27040.0,824292.0,1572,4220.0,Minimum not met.
110,Mauritania,MAU,130.0,3677293,1523335.0,1061515.0,72942.0,20870,15870.0,5000.0,...,728.0,30.0,39.0,3585000.0,1186.0,16710.0,1030700.0,754,5002.0,Minimum not met.
111,Suriname,SUR,132.0,585824,131700.0,77100.0,3030.0,2270,2170.0,100.0,...,0.0,55.0,67.0,1439.0,393.0,8547.0,163820.0,386,1907.0,1200
112,Waynes World,None,NaN,60069020,NaN,NaN,NaN,524358,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None